import type { NextPage, } from "next";
import Head from "next/head";

const Home: NextPage = () => {
    return (
        <div className="bg-red-500">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <p className="text-2xl">sdssdsd2233dsddssdsddssd</p>
            </main>
        </div>
    );
};

export default Home;
