import type { NextPage, } from "next";
import Head from "next/head";
import Link from "next/link";
import PageLayout from "./_components/PageLayout";

const Home: NextPage = () => {
    return (
        <div className="bg-red-500">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <PageLayout>
                    <p className="text-2xl">Home Page</p>
                    <Link href="docs/installation">Installation</Link>
                    <Link href="docs/hello">Hello</Link>
                </PageLayout>
            </main>
        </div>
    );
};

export default Home;
