import Button from "@components/atoms/Button/Button";
import type { NextPage, } from "next";
import Head from "next/head";
 
import Hero from "./_components/Hero";
import LayoutPage from "./_components/layouts/LayoutPage";
import SecondaryFeatures from "./_components/SecondaryFeatures";
 
const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                <LayoutPage>
                  
                    <Hero />
                    <SecondaryFeatures />

                    Brad Frost Atomic Design

                    Support Almost -All- Edge Case Scenario

                    Flexible

                    <section>
                        Scale and Maintanability
                        Atomic Desing



                    </section>


                    <section>
                        Dont re-invet the wheel


                        xs sm md lg xl xl2 xl3
                    </section>


                    TailwindCSS Friendly
                    Customise

                    <section>
                        <div>
                    Button
                    Input
                    Checkox
                    Text
                        </div>

                        <div>
                        Playground
                        </div>
                    </section>


                    <section className="flex justify-between bg-blue-600">
                        <div>
                            Connect with Community
                        </div>

                        <Button label="Join Atomic React" />
                  
                    </section>

                </LayoutPage>

               

              
            </div>
        </div>
    );
};

export default Home;
